version: '3.6'
services:
  java:
    build: ./docker/java/
#    ports:
#      - 8080:8080
    tty: true
    volumes:
      - ./src/java:/usr/local/java/:cached

  cpp:
    build: ./docker/cpp/
#    ports:
#      - 8080:8080
    tty: true
    volumes:
      - ./src/cpp:/usr/local/cpp/:cached

  vbnet:
    build: ./docker/vbnet/
    volumes:
      - ./src/vbnet:/usr/local/vbnet/:cached
    tty: true
    ports:
     - 8000:80