version: '3.6'
services:
  java:
    build: ./docker/java/
#    ports:
#      - 8080:8080
    tty: true
    volumes:
      - ./src/java:/usr/local/src/java:cached

  cpp:
    build: ./docker/cpp/
#    ports:
#      - 8080:8080
    tty: true
    volumes:
      - ./src/cpp:/usr/local/src/:cached

  vbnet:
    build: ./docker/vbnet/
    volumes:
      - ./src/vbnet:/usr/local/src:cached
    tty: true
    ports:
      - 8000:80