FROM mcr.microsoft.com/dotnet/sdk:7.0

# install nodejs
#RUN curl -sL https://deb.nodesource.com/setup_12.x | bash - \
#    && apt-get install -y nodejs

# source
# RUN mkdir /usr/local/src
WORKDIR /usr/local/src
